name: Build and Release Piyaa App

on:
  workflow_dispatch: 

jobs:
  build-and-release:
    runs-on: windows-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Bring Files to Root Directory
        shell: pwsh
        run: |
          $subfolder = Get-ChildItem -Directory | Where-Object { $_.Name -ne '.github' } | Select-Object -First 1
          if ($subfolder -and (Test-Path "$($subfolder.FullName)\package.json")) {
              Write-Host "Moving files from $($subfolder.Name) to root..."
              Move-Item "$($subfolder.FullName)\*" . -Force
              Remove-Item $subfolder.FullName -Recurse -Force
          }

      - name: Install Dependencies
        run: |
          npm cache clean --force
          npm install --force
          npm install @rollup/rollup-win32-x64-msvc --save-dev --force

      - name: Create secret .env file
        shell: bash
        run: |
          cat << 'EOF' > .env
          ${{ secrets.ENV_FILE }}
          EOF

      - name: Build the Code
        run: npm run build

      - name: Build and Publish to GitHub Releases
        run: npx electron-builder --win -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
