name: Build and Release Piyaa App

on:
  workflow_dispatch: 

jobs:
  build-and-release:
    runs-on: windows-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: |
          cd Piyaa--CA-Final-Companion
          npm install

      - name: Create secret .env file
        shell: bash
        run: |
          cd Piyaa--CA-Final-Companion
          cat << 'EOF' > .env
          ${{ secrets.ENV_FILE }}
          EOF

      - name: Build the Code
        run: |
          cd Piyaa--CA-Final-Companion
          npm run build

      - name: Build and Publish to GitHub Releases
        run: |
          cd Piyaa--CA-Final-Companion
          npx electron-builder --win -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
